version: '3'

services:
  esdb-node:
    image: eventstore/eventstore:lts
    container_name: esdb-node
    ports:
      - "2113:2113"
      - "1113:1113"
    command: >
      --insecure
      --run-projections=All
      --enable-external-tcp
      --enable-atom-pub-over-http
